#!/bin/sh
echo Pulling..
git pull
echo Running Jekyll to generate site..
jekyll --no-auto
echo Making backup of Jekyll site..
rm -rf /tmp/_site
mv _site /tmp
echo Adding any new files to repo..
git add -A
echo Commit message?
read commit_message
echo Committing..
git commit -a -m "$commit_message"
echo Pushing..
git push
echo Updating gh-data branch..
git checkout gh-data
git pull
echo Switching to gh-pages branch..
git checkout gh-pages
echo Restoring Jekyll site backup..
cp -R /tmp/_site/* .
echo Adding any new files to repo..
git add -A
echo Pulling..
git pull
echo Committing..
git commit -a -m "$commit_message"
echo Pushing..
git push
echo Switching to master branch..
git checkout master
echo Done!
